### ISSUE TITLE
Question about optional reset module

### ISSUE THREAD

**Issue by poweihuang17** [ucb-bar/generator-bootcamp#17]
HI, in example of optional reset in 3.1,  it said "If resetValue = None, which is the default, the register will have no reset value and be initialized to garbage. ". 
However, the generated code still contains an always block and doesn't have any reset.  The  code now is not synthesizable and may be buggy if used. Why don't we just use assertion and don't generate code in that situation?
```
module cmd9WrapperHelperDelayBy1( // @[:@3.2]
  input         clock, // @[:@4.4]
  input         reset, // @[:@5.4]
  input  [15:0] io_in, // @[:@6.4]
  output [15:0] io_out // @[:@6.4]
);
  reg [15:0] reg$; // @[cmd9.sc 9:12:@8.4]
  reg [31:0] _RAND_0;
  assign io_out = reg$;
`ifdef RANDOMIZE
  integer initvar;
  initial begin
    `ifndef verilator
      #0.002 begin end
    `endif
  `ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {1{$random}};
  reg$ = _RAND_0[15:0];
  `endif // RANDOMIZE_REG_INIT
  end
`endif // RANDOMIZE
  always @(posedge clock) begin
    reg$ <= io_in;
  end
endmodule
```

**Comment by poweihuang17** [comment]
class DelayBy1(resetValue: Option[UInt] = None) extends Module {
    val io = IO(new Bundle {
        val in  = Input( UInt(16.W))
        val out = Output(UInt(16.W))
    })
    val reg = if (resetValue.isDefined) { // resetValue = Some(number)
        RegInit(resetValue.get)
    } else { //resetValue = None
        Reg(UInt())
    }
    reg := io.in
    io.out := reg
}

println(getVerilog(new DelayBy1))
println(getVerilog(new DelayBy1(Some(3.U))))

**Comment by poweihuang17** [comment]
This is the original code.

**Comment by grebe** [comment]
What you are describing is the desired behavior.

Registers without resets are synthesizable. As you say, it may introduce bugs if the garbage initial value is used in some undesirable way, but in some situations registers without reset values may be OK.

In the case of this module, imagine that there is a block that reads the value of `io.out`, but only does so several cycles after `io.in` is valid data (perhaps `io.in` is valid 2 cycles after reset and `io.out` is read 3 cycles after reset).

Resets can add extra overhead, especially because chisel resets are synchronous.

**Comment by poweihuang17** [comment]
@grebe Thank you for your explanation!
